### ISSUE TITLE
Remove jq command

### ISSUE THREAD

**Issue by soichih** [brain-life/app-networkneuro#3]
You don't need to include jq binary with our apps anymore. It's installed in PATH on all of our resources.

This line 

> https://github.com/brain-life/app-networkneuro/blob/master/main#L6

should be updated to
 
```
fsdir=`jq -r '.fsdir' config.json`
```

Also, is `preprocess.sh` still used?

**Comment by bcmcpher** [comment]
I can drop that.

No, I'll probably drop it once it's running. I was trying to separate it
out but it kept messing up the path.

Brent
